spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
  jpa:
    properties:
      hibername:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
